#!/bin/sh
# this is run out of chiark:~ijackson/junk/crontab.chiark

set -e
cd /home/ijackson/public-html/autopkgtest/testing/

#rmvia=true

find *					\
	-maxdepth 2			\
	-mindepth 2			\
	\( 				\
		   -name src		\
		-o -name tmp.\*		\
		-o -type d		\
		-o -size +100k		\
	\)				\
	-mtime +3			\
	-print0				\
 | xargs -tr0 $rmvia rm -rf --

find *					\
	-maxdepth 1			\
	-mindepth 1			\
	-type d				\
	-mtime +100			\
	-print0				\
 | xargs -tr0 $rmvia rm -rf --

