#!/bin/sh
# usage: .../manual-test-one-source <package-name>
set -ex
cd /home/iwj/adt-play
PATH=/home/iwj/autopkgtest/runner:/usr/local/sbin:/usr/sbin:$PATH
export PATH
adt-testreport-onepackage /home/iwj/adt-play/onepackage-config adtrun_extra_opts=--built-binaries-filter=__ interactive=false target=binary-amd64 pkg=$1
